name: on-push
on:
  push:
    branches:
      - "main"
      - "foo"
    tags:        
      - v1
      - v1.*
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo This job runs on push to main and foo branch and on tag v1, v1.0, v1.1 to v1.9
