name: service-containers
on:
  push:
    branches:
      - "main"
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    env:
      DATABASE_NAME: my_database
      DATABASE_USER: foo_user
      DATABASE_PASSWORD: password
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
    steps:
      - name: Install psql client
        run: apt-get -y update && apt-get -y install postgresql-client
      - name: Connect to PostgreSQL
        env: 
          PGPASSWORD: ${{ env.DATABASE_PASSWORD }}
        run: psql -U ${{ env.DATABASE_USER }} -d ${{ env.DATABASE_NAME }} -h postgres -c 'select * from information_schema.tables;'
